### ISSUE TITLE
有没有停止扫描的接口

### ISSUE THREAD

**Issue by zhengxiangke** [xuexiangjys/XQRCode#11]
现在有个需求 要主动停止扫描 请问有这样的接口吗

**Comment by zhengxiangke** [comment]
要主动停止扫描和再次扫描需求 有提供接口吗  因为我如果同时扫描和系统拍照的话 有时报相机聚焦错误 估计是干扰了 所以我想在系统拍照的时候 停止扫描

**Comment by xuexiangjys** [comment]
系统拍照的时候，直接把二维码扫描的页面结束掉不就停止扫描了嘛 @zhengxiangke

**Comment by zhengxiangke** [comment]
需求是在扫码页有个拍照的按钮 我点击拍照就要把扫码停止  所以不能把页面关了

**Comment by xuexiangjys** [comment]
要想停止扫描目前只能结束页面，没有其他API。再说了，二维码扫描本身就可以做成fragment或者其他类型的view，并不是一个window，完全可以在系统拍照时关闭，待系统拍照结束时再显示。本身二维码页面如果在的话，肯定是占有了camera的引用，关闭是最好的方法。
