### ISSUE TITLE
请问大佬这个二维码为啥扫不出来？

### ISSUE THREAD

**Issue by okayFan** [xuexiangjys/XQRCode#12]
![image](https://user-images.githubusercontent.com/20924164/63137440-d9ed7500-c008-11e9-9fee-f4918cc8bcf3.png)

**Comment by xuexiangjys** [comment]
本库采用的是zxing解码，你这个二维码是阿里自己生成的，格式可能是自己定制的，不在zxing的支持列表中，反正我拿微信扫一扫也没扫出来，不信你自己试试。
