### ISSUE TITLE
提个疑问

### ISSUE THREAD

**Issue by HoneyWorld** [xuexiangjys/XQRCode#13]
当二维码不清晰或者是模糊时，对识别率有影响，像下面这种

![4](https://user-images.githubusercontent.com/13584168/67656168-fa816600-f98d-11e9-8e39-bebfb66f565d.jpg)
![1](https://user-images.githubusercontent.com/13584168/67656169-fb19fc80-f98d-11e9-8d08-9f961568bdc0.jpg)
![2](https://user-images.githubusercontent.com/13584168/67656170-fb19fc80-f98d-11e9-92fb-6116ee0bae0c.jpg)
![3](https://user-images.githubusercontent.com/13584168/67656171-fb19fc80-f98d-11e9-840a-374a07792488.jpg)
![5](https://user-images.githubusercontent.com/13584168/67656172-fbb29300-f98d-11e9-9c86-3b99021f55fd.jpg)

**Comment by xuexiangjys** [comment]
上面的二维码是非常好扫描的，没有影响。
