### ISSUE TITLE
有时会识别不出来，退出应用后，重新进来又正常了

### ISSUE THREAD

**Issue by HoneyWorld** [xuexiangjys/XQRCode#14]
我红米note7，测试，打开你的示例apk进行识别，刚开始识别很快，但是偶发的会识别不出来，然后，退出应用重新进来又变得很快，我录了一个小视频放到云盘上了，你有时间可以看看
链接: https://pan.baidu.com/s/1fQx1VymvKyJY2b289txz-g 
提取码: qn7w

**Comment by xuexiangjys** [comment]
我看了一下，你使用的apk是下载的apk，那是我1月的版本，最新的版本我忘记上传了，刚上传，你可以重新下载一下体验
