### ISSUE TITLE
进入“选择二维码进行解析”之后选择图片，应用闪退

### ISSUE THREAD

**Issue by lzz122** [xuexiangjys/XQRCode#18]
在AS自带的模拟机上运行，运行的是作者给出的apk安装包或者直接运行AS项目，进入“选择二维码进行解析”选择图片，之后就闪退（其它功能正常）ps：奇怪的是真机不会闪退
![Screenshot_1588477093](https://user-images.githubusercontent.com/39009430/80898203-5ceb6280-8d33-11ea-85f2-f1647647e8ab.png)
但是XUI不会，正常运行。不知道是不是二者版本不一样

**Comment by xuexiangjys** [comment]
你应该把错误日志贴出来,这样才能帮你解决问题

**Comment by lzz122** [comment]
不好意思，
崩溃时的 log是这样的：
1️⃣ E/AndroidRuntime: FATAL EXCEPTION: main
2️⃣   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65648, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/chart.png flg=0x1 }} to activity {com.xuexiang.xqrcodedemo/com.xuexiang.xqrcodedemo.activity.MainActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/chart.png"
3️⃣  Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/chart.png"
大意是说选择了图片的结果传递给MainActivity的时候失败了？
我经验不足不知道可能是哪里出了问题，详细的log如下：
![批注 2020-05-03 174911](https://user-images.githubusercontent.com/39009430/80911099-be78f480-8d66-11ea-81ec-c18d66333b5f.jpg)

**Comment by xuexiangjys** [comment]
之前的PathUtils工具类没有更新,还存在一些兼容性的bug:
最新的提交已修复该bug:
6d273e441adffe50bb9ea44e4530474f7c916062
