### ISSUE TITLE
是否支持全屏扫码

### ISSUE THREAD

**Issue by yanpengqing** [xuexiangjys/XQRCode#24]
rt

**Comment by yanpengqing** [comment]
或者可以自定义扫码界面大小（半屏或者指定高度），目前是全屏的，自定义界面只是在扫码组件上叠加控件而已。

**Comment by xuexiangjys** [comment]
你自己自定义啊，你想怎么扫就怎么扫：
https://github.com/xuexiangjys/XQRCode#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8C%E7%BB%B4%E7%A0%81%E6%89%AB%E6%8F%8F
