### ISSUE TITLE
关于声音和几个类丢失

### ISSUE THREAD

**Issue by niewenlong123** [xuexiangjys/XQRCode#5]
兄台，，，有几个类比如IntentUtils，ClickUtils类没有，，，还有就是能不能加上声音提示，谢谢

**Comment by niewenlong123** [comment]
我找了很多类，发现你提供的  系统相册识别二维码效果非常好，谢谢

**Comment by niewenlong123** [comment]
sorry,是我没看清楚，原来是引用了类库，，，  只有一个问题，就是如何设置声音

**Comment by xuexiangjys** [comment]
扫码的声音有一个默认的“叮”的声音。声音的设置目前还没有开放出API，因为还没人提这种要求

**Comment by niewenlong123** [comment]
好的，谢谢
