### ISSUE TITLE
扫描次数问题

### ISSUE THREAD

**Issue by zhengxiangke** [xuexiangjys/XQRCode#6]
一次扫成功后 怎么设置继续扫描

**Comment by zhengxiangke** [comment]
修改扫码框的宽高之后 不灵敏了 很难扫

**Comment by zhengxiangke** [comment]
多次扫描 我已经知道了 就是修改扫码框的宽高之后 不灵敏了 很难扫  自定义布局

**Comment by xuexiangjys** [comment]
每次扫描不结束页面就行了

**Comment by zhengxiangke** [comment]
这个我已经解决了 可是我自定义扫码区域 我用你这个layout_custom_camera  修改 这里的<com.xuexiang.xqrcode.view.ViewfinderView
    android:id="@+id/viewfinder_view"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:inner_corner_color="@color/scan_corner_color"
    app:inner_corner_length="30dp"
    app:inner_corner_width="5dp"
    app:inner_marginTop="0dp"
    app:inner_scan_bitmap="@mipmap/ic_scan_image"
    app:inner_scan_isCircle="false"
    app:inner_scan_speed="10"
    app:inner_height="240dp"
    app:inner_width="240dp" />
宽高后 发现扫码不灵敏了  其他没改

**Comment by xuexiangjys** [comment]
光关闭还是不行的，还是要修改源码才行

**Comment by xuexiangjys** [comment]
和这个没关系，要想支持重复扫描的话，还需要我修改源码才行

**Comment by zhengxiangke** [comment]
重复扫描 我做到了           //扫描多次
            Message messageRestart = Message.obtain(mCaptureFragment.getHandler(), com.xuexiang.xqrcode.R.id.restart_preview, null);
            messageRestart.sendToTarget();  现在的问题是 我修改扫码框大小后 扫描不灵敏了

**Comment by xuexiangjys** [comment]
并没有，我的扫描效果很好

**Comment by xuexiangjys** [comment]
最新版本1.0.3已支持重复扫描，详细参见demo

**Comment by zhengxiangke** [comment]
问个问题  我如果要自定义扫码区域的话 <com.xuexiang.xqrcode.view.ViewfinderView
android:id="@+id/viewfinder_view"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
app:inner_corner_color="@color/scan_corner_color"
app:inner_corner_length="30dp"
app:inner_corner_width="5dp"
app:inner_marginTop="0dp"
app:inner_scan_bitmap="@mipmap/ic_scan_image"
app:inner_scan_isCircle="false"
app:inner_scan_speed="10"
app:inner_height="240dp"
app:inner_width="240dp" />  是不是只要修改你的layout就可以了 其他不需要改把 我看都是动态获取loyout的属性的 在获取扫码区域的那个方法上 是不是其他不用改

**Comment by xuexiangjys** [comment]
嗯，不建议你修改源码

**Comment by zhengxiangke** [comment]
方便加我QQ吗  2285032587
