### ISSUE TITLE
自定义扫码区域位置

### ISSUE THREAD

**Issue by zhengxiangke** [xuexiangjys/XQRCode#7]
自定义扫码区域位置 我改变你那个自定义布局 扫码框大小 和 margintop后 识别率 变小  其他没动

**Comment by zhengxiangke** [comment]
自定义扫码区域位置 我改变你那个自定义布局 扫码框大小 和 margintop后 识别率 变小 其他没动

<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <SurfaceView
        android:id="@+id/preview_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <com.xuexiang.xqrcode.view.ViewfinderView
        android:id="@+id/viewfinder_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:inner_corner_color="@color/colorPrimaryDark"
        app:inner_corner_length="30dp"
        app:inner_corner_width="5dp"
        app:inner_marginTop="10dp"
        app:inner_scan_bitmap="@mipmap/kakalib_scan_ray"
        app:inner_scan_isCircle="false"
        app:inner_scan_speed="10"
        android:layout_marginBottom="@dimen/dp_20"
        app:inner_height="240dp"
        app:inner_width="280dp" />



</RelativeLayout>

**Comment by zhengxiangke** [comment]
比如你的demo  我如果定制化扫描界面中改动扫码框的宽高  和margintop 扫码就不灵敏了  其他没动  请问这事怎么回事呀

**Comment by xuexiangjys** [comment]
demo里面设的是1秒钟扫码间隙。扫码不灵敏有多种原因，有设备问题，也有其他很多问题，调整到最合适的就行了。ps:我设置的效果就蛮好的，至于为什么你不灵敏你还是自己找找原因吧

**Comment by zhengxiangke** [comment]
对 你设置的自定义扫码区域是最好的 <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <SurfaceView
        android:id="@+id/preview_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <com.xuexiang.xqrcode.view.ViewfinderView
        android:id="@+id/viewfinder_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:inner_corner_color="@color/scan_corner_color"
        app:inner_corner_length="30dp"
        app:inner_corner_width="5dp"
        app:inner_marginTop="120dp"
        app:inner_scan_bitmap="@mipmap/ic_scan_image"
        app:inner_scan_isCircle="false"
        app:inner_scan_speed="10"
        app:inner_height="300dp"
        app:inner_width="300dp" />

</FrameLayout>

但是我改了你的扫码区域 <com.xuexiang.xqrcode.view.ViewfinderView
        android:id="@+id/viewfinder_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:inner_corner_color="@color/scan_corner_color"
        app:inner_corner_length="30dp"
        app:inner_corner_width="5dp"
        app:inner_marginTop="10dp"
        app:inner_scan_bitmap="@mipmap/ic_scan_image"
        app:inner_scan_isCircle="false"
        app:inner_scan_speed="10"
        app:inner_height="240dp"
        app:inner_width="240dp" /> 扫码就不灵敏了 请问怎么解决

**Comment by xuexiangjys** [comment]
话我不想重复，你给你扫码区域我也试过了，完全没有问题。说句不好听的，饭一定要嚼烂了喂到你嘴里吃吗？
